#!/bin/sh

echo "Assembling!"
mkdir -p /opt/app-root/www
cp -Rf /tmp/src/. /opt/app-root/www
cd /opt/app-root/www

if [ "$(ls /tmp/artifacts/node_modules 2>/dev/null)" ]; then
    mv /tmp/artifacts/node_modules .
fi

npm install
node_modules/node-sass/bin/node-sass styles.scss > styles.css