#!/bin/sh

echo "Assembling!"

mkdir -p /opt/app-root/www
cp -Rf /tmp/src/. /opt/app-root/www

mkdir /opt/app-root/src/passwords
date | md5sum > /opt/app-root/src/passwords/pwd1
echo "Generated password $(cat /opt/app-root/src/passwords/pwd1)"

